services:
  ww_redis_users:
    image: redis:latest
    container_name: ww_redis_users
    ports:
      - "5555:6379"
    volumes:
      - /data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      - ww-network

  postgres:
    container_name: ww_pg_sql
    image: postgres:latest
    environment:
      POSTGRES_USER: dama_team
      POSTGRES_PASSWORD: dama_team
      POSTGRES_DB: wanderwave_db
      PGDATA:  /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ww-network
    restart: unless-stopped

networks:
  ww-network:
    driver: bridge


volumes:
  postgres: